In [1]:
import pandas as pd 
import numpy as np 
import os

In [2]:
synth_img = '/data/7TB/nick/ai_readi_v3/synth_oct_32/'
df = pd.concat([pd.read_csv(synth_img + x + '.csv', index_col=0) for x in ['train', 'val', 'test']]).reset_index().drop(columns=['index'])

In [3]:
df

,Cirrus,Maestro2,Spectralis,Triton,Macula,Optic Disc,Wide Field,L,R,AMD,DR,GL,filepath
0,0,0,1,0,1,0,0,1,0,0,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//train...
1,0,0,0,1,1,0,0,1,0,0,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//train...
2,0,0,0,1,1,0,0,1,0,0,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//train...
3,1,0,0,0,0,1,0,0,1,0,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//train...
4,0,0,0,1,0,1,0,0,1,0,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//train...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56507,1,0,0,0,0,1,0,1,0,0,1,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//test/...
56508,1,0,0,0,0,1,0,1,0,0,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//test/...
56509,0,1,0,0,0,0,1,0,1,0,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//test/...
56510,0,1,0,0,1,0,0,1,0,0,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//test/...
56511,0,1,0,0,1,0,0,1,0,1,0,0,/data/7TB/nick/ai_readi_v3/synth_oct_32//test/...

# Create Image Dataset
### retinal_oct

In [4]:
base = '/data/7TB/nick/synth_ai_readi_oct'

# Top level directory
os.makedirs(base, exist_ok=True)

# Modality-specific directories
os.makedirs(os.path.join(base, 'clinical_data'), exist_ok=True)
os.makedirs(os.path.join(base, 'retinal_oct'), exist_ok=True)

# Image-type directories
os.makedirs(os.path.join(base, 'retinal_oct', 'structural_oct'), exist_ok=True)

In [5]:
pd.read_csv('/data/7TB/nick/ai_readi_v3/resized_retinal_oct/updated_manifest.csv')#[['manufacturer', 'manufacturers_model_name']].value_counts()

,Unnamed: 0,person_id,manufacturer,manufacturers_model_name,anatomic_region,imaging,laterality,height,width,number_of_frames,pixel_spacing,slice_thickness,sop_instance_uid,filepath,reference_instance_uid,reference_filepath,middle_slice
0,0,1001,Heidelberg,Spectralis,Optic Disc,OCT,L,512,512,27,Varies by frame,Not reported,1.3.6.1.4.1.33437.11.4.7587979.98316546453556....,/resized_retinal_oct/structural_oct/heidelberg...,1.3.6.1.4.1.33437.11.4.7587979.98316546453553....,/retinal_photography/ir/heidelberg_spectralis/...,13
1,1,1001,Heidelberg,Spectralis,Optic Disc,OCT,R,512,512,27,Varies by frame,Not reported,1.3.6.1.4.1.33437.11.4.7587979.86599875670058....,/resized_retinal_oct/structural_oct/heidelberg...,1.3.6.1.4.1.33437.11.4.7587979.86599875670055....,/retinal_photography/ir/heidelberg_spectralis/...,13
2,2,1001,Heidelberg,Spectralis,Macula,OCT,L,512,512,60,"[0.003872, 0.01206]",0.128469,1.3.6.1.4.1.33437.11.4.7587979.86599875670063....,/resized_retinal_oct/structural_oct/heidelberg...,1.3.6.1.4.1.33437.11.4.7587979.86599875670060....,/retinal_photography/ir/heidelberg_spectralis/...,29
3,3,1001,Heidelberg,Spectralis,Macula,OCT,L,512,512,61,"[0.003872, 0.012094]",0.128217,1.3.6.1.4.1.33437.11.4.7587979.98316546453560....,/resized_retinal_oct/structural_oct/heidelberg...,1.3.6.1.4.1.33437.11.4.7587979.98316546453557....,/retinal_photography/ir/heidelberg_spectralis/...,30
4,4,1001,Heidelberg,Spectralis,Macula,OCT,R,512,512,61,"[0.003872, 0.011637]",0.12634,1.3.6.1.4.1.33437.11.4.7587979.66636867678269....,/resized_retinal_oct/structural_oct/heidelberg...,1.3.6.1.4.1.33437.11.4.7587979.66636867678266....,/retinal_photography/ir/heidelberg_spectralis/...,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56472,56472,7818,Zeiss,Cirrus,Optic Disc,OCT,R,512,512,200,"[0.001953125, 0.03015075]",0.03015075,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/resized_retinal_oct/structural_oct/zeiss_cirr...,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/retinal_photography/ir/zeiss_cirrus/7818/7818...,99
56473,56473,7818,Zeiss,Cirrus,Macula,OCT,L,512,512,128,"[0.001953125, 0.01174168]",0.01174168,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/resized_retinal_oct/structural_oct/zeiss_cirr...,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/retinal_photography/ir/zeiss_cirrus/7818/7818...,63
56474,56474,7818,Zeiss,Cirrus,Macula,OCT,R,512,512,128,"[0.001953125, 0.01174168]",0.01174168,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/resized_retinal_oct/structural_oct/zeiss_cirr...,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/retinal_photography/ir/zeiss_cirrus/7818/7818...,63
56475,56475,7818,Zeiss,Cirrus,"Macula, 6 x 6",OCT,L,512,512,350,"[0.001953125, 0.01719198]",0.01719198,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/resized_retinal_oct/structural_oct/zeiss_cirr...,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/retinal_photography/ir/zeiss_cirrus/7818/7818...,174
56476,56476,7818,Zeiss,Cirrus,"Macula, 6 x 6",OCT,R,512,512,350,"[0.001953125, 0.01719198]",0.01719198,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/resized_retinal_oct/structural_oct/zeiss_cirr...,1.2.276.0.75.2.2.42.224860851738134.2025050414...,/retinal_photography/ir/zeiss_cirrus/7818/7818...,174

In [6]:
manifest = df.copy()
df['participant_id'] = np.nan
df.loc[:, 'height'] = 512
df.loc[:, 'width'] = 512
df.loc[:, 'number_of_frames'] = 1
df.loc[:, 'pixel_spacing'] = np.nan
df.loc[:, 'slice_thickness'] = np.nan
df.loc[:, 'sop_instance_uid'] = np.nan
df.loc[:, 'reference_instance_uid'] = np.nan
df.loc[:, 'reference_filepath'] = np.nan

#
df['manufacturers_model_name'] = df[['Spectralis', 'Maestro2', 'Triton', 'Cirrus']].idxmax(axis=1)
manu_map = {'Spectralis':'Heidelberg', 'Maestro2':'Topcon', 'Triton':'Topcon', 'Cirrus':'Zeiss'}
df['manufacturer'] = df['manufacturers_model_name'].apply(lambda x: manu_map[x])
df['laterality'] = df[['L', 'R']].idxmax(axis=1)
df['anatomic_region'] = df[['Macula', "Optic Disc", "Wide Field"]].idxmax(axis=1)
df['imaging'] = 'OCT'

In [7]:
import pydicom
from pydicom.dataset import Dataset, FileDataset
from pydicom.uid import generate_uid, ExplicitVRLittleEndian, OphthalmicPhotography8BitImageStorage
from PIL import Image
import datetime

def create_ophthalmic_dicom(data, patient_id):
    patient_name="DOE^JOHN"

    # select directory based on equipment
    manu = (data['manufacturer'] + '_' + data['manufacturers_model_name']).lower()

    #
    output_dicom_path = os.path.join(base, 'retinal_oct/structural_oct', manu, str(patient_id))
    os.makedirs(output_dicom_path, exist_ok=True)

    # Read Image
    img = Image.open(data['filepath']).convert("L")
    pixel_array = np.array(img)

    rows, cols = pixel_array.shape

    # Create File Meta Information
    file_meta = pydicom.Dataset()
    file_meta.MediaStorageSOPClassUID = OphthalmicPhotography8BitImageStorage
    file_meta.MediaStorageSOPInstanceUID = generate_uid()
    file_meta.ImplementationClassUID = generate_uid()

    # Create DICOM Dataset
    ds = FileDataset(output_dicom_path, {}, file_meta=file_meta, preamble=b"\0" * 128)

    # Set the transfer syntax
    ds.is_little_endian = True
    ds.is_implicit_VR = False

    # Patient and Study Information
    ds.PatientName = patient_name
    ds.PatientID = str(patient_id)
    ds.StudyInstanceUID = generate_uid()
    ds.SeriesInstanceUID = generate_uid()
    ds.SOPInstanceUID = file_meta.MediaStorageSOPInstanceUID
    ds.SOPClassUID = file_meta.MediaStorageSOPClassUID

    # Date and Time
    dt = datetime.datetime.now()
    ds.StudyDate = dt.strftime('%Y%m%d')
    ds.StudyTime = dt.strftime('%H%M%S')

    # Modality and Image Type
    ds.Manufacturer = data['manufacturer']
    ds.ManufacturerModelName = data['manufacturers_model_name']
    ds.ImageType = ['ORIGINAL', 'PRIMARY']
    ds.PhotometricInterpretation = 'MONOCHROME1'
    ds.SamplesPerPixel = 1
    ds.Rows = rows
    ds.Columns = cols
    
    ds.BitsAllocated = 8
    ds.BitsStored = 8
    ds.HighBit = 7
    ds.PixelRepresentation = 0
    ds.PlanarConfiguration = 0 

    # Ophthalmic-specific tags (simplified example)
    ds.ImageLaterality = data['laterality']  # 'R'ight, 'L'eft, 'U'nspecified
    ds.NumberOfFrames = 1

    # Set the Pixel Data
    ds.PixelData = pixel_array.tobytes()

    # Save the DICOM file
    ds.file_meta.TransferSyntaxUID = ExplicitVRLittleEndian

    filename = "_".join([str(patient_id), data['manufacturers_model_name'], data['anatomic_region'], data['imaging'], ds.SOPInstanceUID]).lower().replace(' ', '_').replace(',', '') + '.dcm'
    output_dicom_path = os.path.join(output_dicom_path, filename)
    
    ds.save_as(output_dicom_path)
    #print(f"DICOM saved to: {output_dicom_path}")

    return output_dicom_path.split(base+'/')[1], ds.SOPInstanceUID

In [8]:
from tqdm import tqdm

df.loc[:, 'sop_instance_uid'] = ''
for i, row in tqdm(df.iterrows(), total=len(df)):
    fp = create_ophthalmic_dicom(row, i)
    df.loc[i, 'filepath'] = fp[0]
    df.loc[i, 'sop_instance_uid'] = fp[1]

/tmp/ipykernel_2977110/617833078.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, 'sop_instance_uid'] = ''
100%|██████████| 56512/56512 [02:41<00:00, 348.98it/s]

In [9]:
row

Cirrus                                                                      0
Maestro2                                                                    1
Spectralis                                                                  0
Triton                                                                      0
Macula                                                                      1
Optic Disc                                                                  0
Wide Field                                                                  0
L                                                                           1
R                                                                           0
AMD                                                                         1
DR                                                                          0
GL                                                                          0
filepath                    /data/7TB/nick/ai_readi_v3/synth_oct_32//test/...
participant_id                                                            NaN
height                                                                    512
width                                                                     512
number_of_frames                                                            1
pixel_spacing                                                             NaN
slice_thickness                                                           NaN
sop_instance_uid
reference_instance_uid                                                    NaN
reference_filepath                                                        NaN
manufacturers_model_name                                             Maestro2
manufacturer                                                           Topcon
laterality                                                                  L
anatomic_region                                                        Macula
imaging                                                                   OCT
Name: 56511, dtype: object

In [10]:
df.loc[:,'participant_id'] = df.index.values
df['participant_id'] = df['participant_id'].astype(int)
df[['participant_id','manufacturer','manufacturers_model_name','laterality','anatomic_region','imaging','height','width', 'sop_instance_uid', 'filepath']].to_csv(os.path.join(base, 'retinal_oct') + '/manifest.tsv', sep='\t')
df[['participant_id','manufacturer','manufacturers_model_name','laterality','anatomic_region','imaging','height','width', 'sop_instance_uid', 'filepath']]

,participant_id,manufacturer,manufacturers_model_name,laterality,anatomic_region,imaging,height,width,sop_instance_uid,filepath
0,0,Heidelberg,Spectralis,L,Macula,OCT,512,512,1.2.826.0.1.3680043.8.498.19001840055253301919...,retinal_oct/structural_oct/heidelberg_spectral...
1,1,Topcon,Triton,L,Macula,OCT,512,512,1.2.826.0.1.3680043.8.498.26880092785827476720...,retinal_oct/structural_oct/topcon_triton/1/1_t...
2,2,Topcon,Triton,L,Macula,OCT,512,512,1.2.826.0.1.3680043.8.498.47132040600085377253...,retinal_oct/structural_oct/topcon_triton/2/2_t...
3,3,Zeiss,Cirrus,R,Optic Disc,OCT,512,512,1.2.826.0.1.3680043.8.498.28389620059083564971...,retinal_oct/structural_oct/zeiss_cirrus/3/3_ci...
4,4,Topcon,Triton,R,Optic Disc,OCT,512,512,1.2.826.0.1.3680043.8.498.43345249385831068447...,retinal_oct/structural_oct/topcon_triton/4/4_t...
...,...,...,...,...,...,...,...,...,...,...
56507,56507,Zeiss,Cirrus,L,Optic Disc,OCT,512,512,1.2.826.0.1.3680043.8.498.49229008524315398738...,retinal_oct/structural_oct/zeiss_cirrus/56507/...
56508,56508,Zeiss,Cirrus,L,Optic Disc,OCT,512,512,1.2.826.0.1.3680043.8.498.10666330542959964774...,retinal_oct/structural_oct/zeiss_cirrus/56508/...
56509,56509,Topcon,Maestro2,R,Wide Field,OCT,512,512,1.2.826.0.1.3680043.8.498.31689569386722901979...,retinal_oct/structural_oct/topcon_maestro2/565...
56510,56510,Topcon,Maestro2,L,Macula,OCT,512,512,1.2.826.0.1.3680043.8.498.64292774148476974099...,retinal_oct/structural_oct/topcon_maestro2/565...
56511,56511,Topcon,Maestro2,L,Macula,OCT,512,512,1.2.826.0.1.3680043.8.498.49528362477862777879...,retinal_oct/structural_oct/topcon_maestro2/565...

# Clinical data (OMOP) for synthetic image dataset
### (only contains observation.csv)

In [14]:
obs = pd.read_csv('/data/7TB/nick/ai_readi_v3/clinical_data/observation.csv', index_col=0)

In [27]:
codes = {'AMD': 374028, 'DR':4174977, 'GL': 437541}
counter = 0
new_obs = []
for name, code in codes.items():
    temp = obs[obs['qualifier_concept_id'] == code]
    cols_same = {col:[] for col in temp.columns if len(temp[col].value_counts()) <= 1}
    cols_new = {col:[] for col in temp.columns if len(temp[col].value_counts()) > 1}

    for i, row in df.iterrows():
        for col in cols_same:
            cols_same[col].append(temp.iloc[0][col])
        
        cols_new['observation_id'].append(int(counter))
        cols_new['person_id'].append(int(row['participant_id']))

        now = datetime.datetime.now()
        omop_date = now.date()                     # date: YYYY-MM-DD
        omop_datetime = now.strftime('%Y-%m-%d %H:%M:%S')  # datetime: string format
    
        cols_new['observation_date'].append(omop_date)
        cols_new['observation_datetime'].append(omop_datetime)
        cols_new['value_as_number'].append(int(row[name]))
        cols_new['value_as_string'].append(str(row[name]))
        cols_new['value_as_concept_id'].append('4188539' if row[name] == 1 else '45878245')
        cols_new['visit_occurrence_id'].append(int(row['participant_id']))
            

        counter += 1

    merged = {**cols_new, **cols_same}
    new_obs.append(pd.DataFrame(merged)[obs.columns])

new_obs = pd.concat(new_obs)

In [28]:
new_obs.to_csv(os.path.join(base, 'clinical_data') + '/observation.csv')

In [30]:
new_obs.shape[0] / 3

56512.0